### ISSUE TITLE
멀티플레이 시 Level 2 부터 소리가 나는 문제

### ISSUE THREAD

**Issue by daryu519** [CSID-DGU/2021-2-OSSProj-OTS-7#100]
![image](https://user-images.githubusercontent.com/90627763/143985191-82cc1313-5149-4459-a9b3-9664b586787a.png)

게임 시작 시 소리가 나지 않다가 스테이지(LEVEL)가 2단계로 바뀌면 소리가 나기 시작합니다.
그 외 배속 재생은 정상 작동

**Comment by kshshkim** [comment]
https://github.com/CSID-DGU/2021-2-OSSProj-OTS-7/pull/103/commits/6e2ce35f54d6a8d2f6f108d96cf3ebed4c78e1f4

해결했습니다.
