### ISSUE TITLE
멀티플레이 시 갑자기 GAME OVER 되는 현상

### ISSUE THREAD

**Issue by daryu519** [CSID-DGU/2021-2-OSSProj-OTS-7#101]
![image](https://user-images.githubusercontent.com/90627763/143985290-2f76d092-fdb5-4b7f-a142-fdb8dcad22a9.png)

오른쪽 화면처럼 게임 시작 초반부에 갑자기 GAME OVER 가 되는 오류 발생

**Comment by kshshkim** [comment]
오른쪽 클라이언트가 연결이 끊기면 게임 오버 처리가 됩니다. 클라이언트쪽 문제로 추정되는데 에러 로그가 없어서 모르겠습니다.

**Comment by kshshkim** [comment]
구버전에서 발생한 버그로 지금은 해결되었습니다.
