### ISSUE TITLE
멀티플레이 시 양쪽 플레이어 모두 GAME OVER 시 '서버와의 연결이 끊어졌습니다.'

### ISSUE THREAD

**Issue by daryu519** [CSID-DGU/2021-2-OSSProj-OTS-7#102]
![image](https://user-images.githubusercontent.com/90627763/143985414-ed00ba6a-5f80-4374-bab3-f795be33e2fc.png)

**Comment by kshshkim** [comment]
서버쪽 로그를 같이 올려주세요
