### ISSUE TITLE
대기열 요청 오류

### ISSUE THREAD

**Issue by daryu519** [CSID-DGU/2021-2-OSSProj-OTS-7#104]
상대 플레이어가 대기열 요청만 하고 게임을 종료해버리면 다른 플레이어 대기열 화면에 계속 남아있습니다.
화면 갱신이 필요한 것 같습니다.
![image](https://user-images.githubusercontent.com/90627763/144004384-bd3f7fba-f757-4c82-a777-02ca0607098b.png)

**Comment by kshshkim** [comment]
https://github.com/CSID-DGU/2021-2-OSSProj-OTS-7/pull/106

해결했습니다.
