### ISSUE TITLE
멀티플레이 게임 도중 다른 쪽 플레이어가 일방적으로 게임을 종료했을 때 발생 오류

### ISSUE THREAD

**Issue by daryu519** [CSID-DGU/2021-2-OSSProj-OTS-7#105]
멀티플레이 시 다른 플레이어가 게임 도중 나가버리면 다른 플레이어 쪽에서 문제가 생깁니다.
1. game이 종료되었는데도 WIN, LOSE 여부가 뜨지 않고 GAMEOVER 메시지가 뜬 채로 멈춰있습니다. 
2. 남은 플레이어가 대기열 요청을 해도 온라인 대기열 창에 표시되지 않습니다.

[ gameover 에서 멈춰 있는 상태 ]
++Sent raw: b'\x81\xfe\x03\t&\x17\xf9\n]5\x8d(\x1c7\xdbmB5\xd5*\x04s\xdb0\x06l\xdbcB5\xc3*\x04s\x98;\x14$\xdb&\x065\x8aiIe\x9c(\x1c7\xc89\x16;\xd9(Jr\x8foJ5\xc3*\x17;\xd9(Ax\x98f\x04-\xd9?\n7\xdbgGc\x8bc^5\xc3*}L\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xccW\n7\xa2:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x13;\xd9?{;\xd9Q\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06"\xd5*\x16J\xd5*}\'\xd5*\x10;\xd9:\n7\xca&\x06\'\xd5*\x13;\xd9:\n7\xcb&\x06%\xd5*\x11;\xd9:\n7\xce&\x06\'\xd5*\x16;\xd99\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xcd&\x06#\xa4&\x06L\xcf&\x06!\xd5*\x16;\xd99\n7\xcc&\x06"\xd5*\x12;\xd9>\n7\xcb&\x06 \xd5*\x11;\xd9=\n7\xce&\x06\'\xd5*\x15;\xd9=\n7\xc9&\x06#\xd5*\x12;\xd9>\n7\xcdW\n7\xa2:\n7\xcf&\x06$\xd5*\x15;\xd9?\n7\xc9&\x06#\xd5*\x12;\xd98\n7\xc9&\x06 \xd5*\x16;\xd9=\n7\xca&\x06$\xd5*\x11;\xd9=\n7\xcd&\x06#\xd5*\x16;\xd99{;\xd9Q\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x11;\xd9:\n7\xc9&\x06\'\xd5*\x15J\xd5*}\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xca&\x06$\xa4&\x06L\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x15;\xd99\n7\xcaW\n7\xa2:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd9:\n7\xc9&\x06\'\xd5*\x16;\xd99{J\xd5*\x04y\x9crRH\x94cHx\xa6cHs\x9cr\x04-\xd99\n7\xdbbI{\x9dUK~\x97ey~\x97nCo\xdb0\x06:\xc8w['
++Sent decoded: fin=1 opcode=1 data=b'{"t": "gd", "d": {"id": "da123", "score": 130, "level": 1, "goal": 5, "matrix": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0], [0, 6, 0, 3, 0, 5, 0, 2, 2, 7, 0, 7, 0, 0, 3, 0, 0, 0, 0, 4, 4], [6, 6, 0, 3, 5, 5, 4, 4, 2, 7, 7, 7, 7, 0, 3, 7, 0, 4, 4, 4, 4], [0, 6, 3, 3, 5, 0, 4, 4, 2, 0, 7, 0, 7, 3, 3, 7, 7, 4, 4, 0, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]], "next_mino_index": 3, "hold_mino_index": -1}}'
++Sent raw: b'\x81\xfe\x03\t\x1c\xe0\x8c\xebg\xc2\xf8\xc9&\xc0\xae\x8cx\xc2\xa0\xcb>\x84\xae\xd1<\x9b\xae\x82x\xc2\xb6\xcb>\x84\xed\xda.\xd3\xae\xc7<\xc2\xff\x88s\x92\xe9\xc9&\xc0\xbd\xd8,\xcc\xac\xc9p\x85\xfa\x8ep\xc2\xb6\xcb-\xcc\xac\xc9{\x8f\xed\x87>\xda\xac\xde0\xc0\xae\x86}\x94\xfe\x82d\xc2\xb6\xcbG\xbb\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xb9\xb60\xc0\xd7\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb)\xcc\xac\xdeA\xcc\xac\xb0,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd5\xa0\xcb,\xbd\xa0\xcbG\xd0\xa0\xcb*\xcc\xac\xdb0\xc0\xbf\xc7<\xd0\xa0\xcb)\xcc\xac\xdb0\xc0\xbe\xc7<\xd2\xa0\xcb+\xcc\xac\xdb0\xc0\xbb\xc7<\xd0\xa0\xcb,\xcc\xac\xd80\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xb8\xc7<\xd4\xd1\xc7<\xbb\xba\xc7<\xd6\xa0\xcb,\xcc\xac\xd80\xc0\xb9\xc7<\xd5\xa0\xcb(\xcc\xac\xdf0\xc0\xbe\xc7<\xd7\xa0\xcb+\xcc\xac\xdc0\xc0\xbb\xc7<\xd0\xa0\xcb/\xcc\xac\xdc0\xc0\xbc\xc7<\xd4\xa0\xcb(\xcc\xac\xdf0\xc0\xb8\xb60\xc0\xd7\xdb0\xc0\xba\xc7<\xd3\xa0\xcb/\xcc\xac\xde0\xc0\xbc\xc7<\xd4\xa0\xcb(\xcc\xac\xd90\xc0\xbc\xc7<\xd7\xa0\xcb,\xcc\xac\xdc0\xc0\xbf\xc7<\xd3\xa0\xcb+\xcc\xac\xdc0\xc0\xb8\xc7<\xd4\xa0\xcb,\xcc\xac\xd8A\xcc\xac\xb0,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb+\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb/\xbd\xa0\xcbG\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbf\xc7<\xd3\xd1\xc7<\xbb\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb/\xcc\xac\xd80\xc0\xbf\xb60\xc0\xd7\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xdb0\xc0\xbc\xc7<\xd0\xa0\xcb,\xcc\xac\xd8A\xbd\xa0\xcb>\x8e\xe9\x93h\xbf\xe1\x82r\x8f\xd3\x82r\x84\xe9\x93>\xda\xac\xd80\xc0\xae\x83s\x8c\xe8\xb4q\x89\xe2\x84C\x89\xe2\x8fy\x98\xae\xd1<\xcd\xbd\x96a'
++Sent decoded: fin=1 opcode=1 data=b'{"t": "gd", "d": {"id": "da123", "score": 130, "level": 1, "goal": 5, "matrix": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0], [0, 6, 0, 3, 0, 5, 0, 2, 2, 7, 0, 7, 0, 0, 3, 0, 0, 0, 0, 4, 4], [6, 6, 0, 3, 5, 5, 4, 4, 2, 7, 7, 7, 7, 0, 3, 7, 0, 4, 4, 4, 4], [0, 6, 3, 3, 5, 0, 4, 4, 2, 0, 7, 0, 7, 3, 3, 7, 7, 4, 4, 0, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]], "next_mino_index": 3, "hold_mino_index": -1}}'
++Sent raw: b'\x81\x96wk]\xf0\x0cI)\xd2MK\x7f\x97\x18Iq\xd0U\x0f\x7f\xcaW\x05(\x9c\x1b\x16'
++Sent decoded: fin=1 opcode=1 data=b'{"t": "go", "d": null}'
++Rcv raw: b'\x89\x04l\x0fi\xf4'
++Rcv decoded: fin=1 opcode=9 data=b'l\x0fi\xf4'
++Sent raw: b'\x8a\x84\xe9;\x86P\x854\xef\xa4'
++Sent decoded: fin=1 opcode=10 data=b'l\x0fi\xf4'
++Rcv raw: b'\x89\x04\x08\xa5\x97d'
++Rcv decoded: fin=1 opcode=9 data=b'\x08\xa5\x97d'
++Sent raw: b'\x8a\x84\x17\x7f\xd3\xa7\x1f\xdaD\xc3'
++Sent decoded: fin=1 opcode=10 data=b'\x08\xa5\x97d'

[ 온라인 대기열 요청한 상태 ]
{'t': 'wl', 'd': []}
hello
++Rcv raw: b'\x81\x14{"t": "wl", "d": []}'
++Rcv decoded: fin=1 opcode=1 data=b'{"t": "wl", "d": []}'
++Sent raw: b'\x81\x96!`zOZB\x0em\x1b@X8@BVo\x03\x04Xu\x01\x0e\x0f#M\x1d'
++Sent decoded: fin=1 opcode=1 data=b'{"t": "wa", "d": null}'
++Rcv raw: b'\x89\x04T\xab\x96$'
++Rcv decoded: fin=1 opcode=9 data=b'T\xab\x96$'
++Sent raw: b'\x8a\x84\x97\xe7\x0b\xb6\xc3L\x9d\x92'
++Sent decoded: fin=1 opcode=10 data=b'T\xab\x96$'
{'t': 'wl', 'd': ['da123']}
waiting
++Rcv raw: b'\x81\x1b{"t": "wl", "d": ["da123"]}'
++Rcv decoded: fin=1 opcode=1 data=b'{"t": "wl", "d": ["da123"]}'
{'t': 'wl', 'd': []}
waiting
++Rcv raw: b'\x81\x14{"t": "wl", "d": []}'
++Rcv decoded: fin=1 opcode=1 data=b'{"t": "wl", "d": []}'

**Comment by kshshkim** [comment]
https://github.com/CSID-DGU/2021-2-OSSProj-OTS-7/pull/106

해결했습니다.
